demo/index.html
* Tweak and improve some of the explanation text (typos, etc.)
* Add headers and more description to Top 20 pages vs. domains, as well as adding explanation to About page to address #75 (This doesn't look perfect, and additional text will inherently look less good, but I think--in theory--the additions are important based on UX testing. I welcome design tweaks, though.)
Fixes #75.
=> More frontend tweaks

404.html
Addresses part of #100.
May God bless Open Sans, and may God bless the United States of America.
=> Simple 404 page

.gitignore, dap.md
This ports and adapts my original DAP cloud-hosting instructions into a guide for publishing the snippet we'll use for this project. 
When the guide is followed, a gzip-compressed, minified version of the current, Universal Analytics version of the DAP snippet is published to:
> https://analytics.usa.gov/dap/dap.min.js
There's also a `dap.js` non-minified version, and a source map at `dap.min.js.map`. All of them are gzipped, and cross-reference each other to allow for in-browser debugging by browsers that support source maps.
I've currently set the cache time for these files to 0 seconds, so that it didn't drive me crazy while testing it, but that **must** be increased after this PR is merged, to minimize costs to our S3 bucket.
=> DAP upload, compression, and publishing instructions

demo/index.html
This adds the site to the DAP, using the hosted DAP snippet I added after #105. The tag is:
```html
<script id="_fed_an_ua_tag" src="https://analytics.usa.gov/dap/dap.min.js"></script>
```
Two notes:
* The page cannot be running at `localhost`, or an error is thrown. It does some brittle domain-splitting that throws an error. I used `ngrok` to create a "normal-looking" domain so that it would work. This should become an upstream issue for the team maintaining the DAP snippet.
* The `id` attribute is required, or an error is thrown. I'm not sure why it is required.
Fixes #81.
=> Add this site to the DAP itself

demo/index.html, js/index.js
This adds a nice little message to the developer console, for anyone who pokes around:
It degrades to plaintext formatting on IE9, 10, and 11 (using some simple user agent detection stuff), where the `%c` trick isn't supported. It should work well on Chrome and Firefox.
Fixes #82.
=> Adds a message to the console

css/public_analytics.css, demo/index.html, sass/public_analytics.css.scss
Makes some copy changes to the About section, and spaces the text out a little better:
This addresses my concern in https://github.com/GSA/analytics.usa.gov/pull/97#issuecomment-70382915 and fixes #80.
=> Tweak copy, and copy spacing

demo/index.html, js/index.js
Fixes #57. Funnily enough, the real number right now is 1.06 billion, which is oddly close to the fake one.
In doing so, I generalized the visits formatting function so that we could easily make new ones with different suffixes. Rather than adding a new block that hits `users.json`, I added a "render" callback to the devices block that totals up the numbers and sticks the formatted number into `#total_visitors`. I stuck an ellipsis into that element so that the fake number doesn't show up while the data is loading.
=> Make the big number real

demo/index.html
Links the About text to the [DAP's privacy FAQ section](http://www.digitalgov.gov/services/dap/common-questions-about-dap-faq/#part-4).
Fixes #123.
=> Link to the DAP's privacy permalink

js/index.js
This should fix #49 instead of creating a separate table, if I understand @nickbristow's requirements.
- each g.bar gets `tabindex="0"` and `aria-label="XXX visits during the hour of XXpm"`
- the chart axes get `aria-hidden="true"`
=> Add ARIA attributes to chart

js/index.js
For some domains and links that we expect to consistently be in the Top 20, and do not expect to be able to make adjustments to their infrastructure in the short term, we hardcode some exceptions to reduce 404s from people clicking through from the Top 20 tabs.
Fixes #69.
=> Hardcode some link exceptions for common websites without permalinks

Makefile, README.md
A new contributor trying to work on this code will quickly run into the issue of the static files needing to be served through an HTTP server. This gives a quick cheap option for doing so locally.
=> Add a 'serve' make command for local testing

Gemfile, Gemfile.lock, Makefile, README.md, _config.yml, _development.yml, index.html
This moves the site away from purely static HTML and uses Jekyll to build the site into static HTML.
The primary motivator here is so that the site can be easily developed to pull from local data, which was previously hardcoded in like 15 places to be `analytics.usa.gov`. I anticipate that this separation will make the site at least a little easier for others to adapt to their own URLs and circumstances, too.
A new `_development.yml` config file allows someone to build the site to assume that the site is at `localhost:4000` and the data at `localhost:3000` at:
```
bundle exec jekyll serve --watch --config=_config.yml,_development.yml
```
The default `bundle exec jekyll serve` will use the production settings, where everything is assumed to be on `analytics.usa.gov`.
I've rewritten the …
=> Convert site to use Jekyll, allow for local data hosting

Makefile, README.md
Taking a page from @shawnbot, take the ugly `jekyll` commands I spawned for development and production use and put them behind a couple of handy `make` commands.
Run the dev server with `--watch` and `--config=_config.yml,_development.yml` with:
```
make dev
```
Build the production site (don't run the server) with:
```
make production
```
I updated the README with docs for both.
=> Simplify Jekyll commands in dev and production

index.html
This lets us get valuable information about how Google sees and indexes analytics.usa.gov. The same verification can be shared to give access to multiple team mambers, so we should only have to do this once.
=> Add Google Webmaster Tools verification tag

index.html
This updates the site to link to the new automatically generated/published report of participating second-level domains. It updates daily, along with the other daily reports.
=> Link to the new SLD CSV

css/public_analytics.css
Not sure if this is a feature or a bug, but I find it a bit distracting.
=> Removing blue outline from bars in chart on click

index.html
This changes our DAP embed code to:
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
```
This takes advantage of the DAP's new [centrally hosted JavaScript code](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/), which means 18f.gsa.gov will automatically get security updates, new features, and other bugfixes automatically.
=> Switch to DAP's new central hosting URL

index.html
We moved to dap@support.digitalgov.gov from dap@gsa.gov
=> Modify DAP contact address

README.md
Updates the deploy command to upload to CSS separately, with an explicit mime type. Still not sure the root cause that made this a problem, but this should be future-proof for our current s3cmd-based upload process.
Fixes #191.
=> Update deploy command to do CSS separately

index.html
Something breaking with & in src. Reverting back to old `<script>` without until issue resolved.
=> Revert back to former DAP script

index.html
Trying this one more time, I am confident it will resolve. The source path now works:
https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&exts=json
**diff makes the & white, but it is there.
=> Add json downloads querystring parameter

Makefile, README.md
This moves the (rather complicated) `s3cmd` deploy command into the `Makefile` to make the new deploy command `make deploy`. It is hardcoded to GSA/18F's specific S3 bucket, with `s3cmd`-specific parameters.
=> Move deploy command into Makefile

README.md, _config_18f_pages.yml, index.html
This uses 18F Pages to give us a staging site, visible right now at https://pages.18f.gov/analytics.usa.gov/.
* I made every URL in the app that pulls assets support a Jekyll `baseurl` for a path prefix.
* I added a `_config_18f_pages.yml` file, a Jekyll settings override file whose filename 18F Pages looks for and will use if present. It sets the `baseurl`, site `url`, and `data_url` for live data.
* Because we store data in S3, not version control, **the staging site uses production data** -- and so the staging site is really only appropriate for previewing front-end changes.
Rather than change our ongoing workflow, I think we should continue developing on `master`, and push the latest stuff or WIP branch over to `18f-pages` whenever we need a public staging URL to share with people. …
=> Create a staging site at pages.18f.gov

css/public_analytics.scss, index.html
This breaks out the data section into a more full-width presentation, with two columns. It links to more CSVs and better data, and drops the direct links to every JSON file. It looks better in some ways, and makes the flow of the page worse in others.
There's other work besides the presentation here -- the work to slim/modify reports in https://github.com/18F/analytics-reporter/pull/124 supports this PR, and some other production server cron-rejiggering was done to make sure we're within quotas, and publishing all the CSVs we want.
This new open data pane emphasizes CSV for nearly everything. We could add JSON links to many things pretty easily. 
Here's a screenshot of what it looks like on this branch - I would love some love from @JuliaWinn and @shawnbot to make this feel better and …
=> Revamp open data on analytics.usa.gov

Makefile, css/public_analytics.scss, index.html, js/index.js
This removes the `10` and `20` from each top table, and restores the Pages/Domains name to the header next to the tabs at the top.
Instead of separating Pages/Domains out below the word "Top" in a different sized font, as it was **before**:
This PR integrates the word into the header and makes it so the tabs switch the word in-place, like in these two shots:
And the Top Downloads section is styled identically:
=> Make "top ____" tables consistent in display

index.html
Both now say "Total visits over the last X to <strong>domains</strong>, including traffic to all pages within that domain"
=> Update language in "30 days" to mirror in "7 days"

js/index.js
Previously threshold was 1.5%, Edge currently has 1.4% of the traffic. As we only expect Edge traffic to increase with time, lowering the % threshold for appearing in the list (vs. being sorted into "Other") addresses this problem. The threshold may need to be adjusted in the future as these numbers change.
=> new % threshold means edge now appears in the list of browsers

index.html, js/index.js
Location data was being rendered with incorrect data, because we were running the international per-country data through the same post-render nesting process that we run the IE and Windows bar charts through.
This wasn't correct, because the Windows chart is "scaled" based on the overall % of Windows within operating systems, and the IE chart is "scaled" based on the overall % of IE within browsers. The international country information is pulling from the same report as its parent -- the nesting is just a visual convenience, without any actual mathematical scaling ramifications.
This change adds support for a `data-scale-to-parent` element for child `<figure>` elements whose bar chart data is meant to be scaled by its parent bar. It is set to `"true"` for the IE and Windows bar charts, …
=> Fixes incorrect location data %'s

index.html
This builds on #148 but makes the language consistent in the other direction, by removing "Total". This has the minor benefit of making the language underneath the 30 day domain tab not line-wrap, which makes the whole section more compact and aesthetically pleasing.
=> Make the "visits" language consistent in the other direction

README.md, _development.yml, fake-json-data/browsers.json, fake-json-data/devices.json, fake-json-data/ie.json, fake-json-data/os.json, fake-json-data/realtime.json, fake-json-data/today.json, fake-json-data/top-cities-realtime.json, fake-json-data/top-countries-realtime.json, fake-json-data/top-domains-30-days.json, fake-json-data/top-domains-7-days.json, fake-json-data/top-downloads-7-days.json, fake-json-data/top-pages-realtime.json, fake-json-data/windows.json
Resolves the issue I raised in https://github.com/18F/analytics.usa.gov/issues/265.
Your localdev version of the dashboard will now look like the following screenshot:
=> Add in fake json to enable a more realistic local development on website

README.md
Re-opening https://github.com/18F/analytics.usa.gov/pull/264 on a newly created branch.  I made the mistake of not re-naming the branch `18f-pages` to a different name, which caused https://github.com/18F/analytics.usa.gov/pull/264 to accidentally close. :cry:
=> Add README instruction to install analytics reporter dependency

_layouts/default.html
The link we conveniently put at the top to the bulk download under the 30 days tab was actually linking to the top-20 download instead of the full one. This fixes that.
=> Fix link to bulk download

_layouts/agencies.html
Instead of "government", a la the previous change to total number of real-time visitors
=> Reflecting "agency" downloads

_layouts/default.html
Switching the downloadable data from "updated every minute" to "updated every two minutes" to reflect the change we made to conserve API calls
=> Reflect every 2 minutes for real-time downloads

_layouts/agencies.html
Addresses #312  . Just fixes the favicon for the agency level pages.
=> Fixed favicon for agency pages

js/index.js
This was leaking a global `us_visits`, and could have caused an issue if the variable was never set because `total_visits - undefined === NaN`.
=> Fix global variable leak

js/index.js
USPS.com has a bad case of sensitivity. This makes the 6 USPS sites showing up in the top 20 work when clicked.
=> Fix some USPS case sensitive URLs

README.md
`http://localhost:4000` is the address of the dashboard when following the Readme. 
I think the original `_development.yml` settings pull data from `/fakedata` ?
=> Updated readme for local dev data location

_development.yml
Based on warning message when running `make dev` 
```
Deprecation: The 'data_source' configuration option has been renamed to 'data_dir'. 
Please update your config file accordingly.
```
=> Changed data_source to data_dir

_layouts/agencies.html, _layouts/default.html, css/public_analytics.scss
This PR addresses https://github.com/18F/analytics.usa.gov/issues/334 and https://github.com/18F/analytics.usa.gov/issues/335.
It simplifies the HTML and Sass for the top navigation (i.e., now only one dropdown vs. the two before that toggled visibility based on screen size) and conserves vertical space on small screens (2 rows instead of 3).
The various states look like this:
**large screen**:
**medium screen**:
**small screen**:
(Note that "About this site" degrades to "About" for small screens for space savings)
=> touch up navbar

README.md
After `make dev` command we can see that command that is run is different than command in README.md.
=> correct command to start jekkyl if someone does not use make

_layouts/agencies.html, _layouts/default.html
The bulk download link on the 30 days tab was linking to just the top 20. This fixes that.
=> Bulk download link wasn't bulk

_includes/data_download.html
We bumped it up from 2 to 3 to support the new agency pages and remain under API quotas.
=> Updates data page to reference 3 minutes instead of 2

js/index.js
I think we fixed this on the irs.gov side. [irs.gov/forms-&-pubs](irs.gov/forms-&-pubs) and [irs.gov/individuals/electronic-filing-pin-request](irs.gov/individuals/electronic-filing-pin-request) should now correctly resolve without the hardcoding.
=> Remove hardcoded link exceptions for irs.gov

_includes/charts.html, _includes/data_download.html, _includes/footer.html, css/public_analytics.scss, js/index.js
**Note:** This depends on https://github.com/18F/analytics-reporter/pull/164 being merged and deployed to production.
This links to the new bulk data reports in https://github.com/18F/analytics-reporter/pull/164 on the `/data` page. Every agency will also get their own scoped version of these reports.
I also re-added the (already generated) JSON report links next to the base `browser`, `os`, `windows`, and `ie` reports, since we do helpful aggregation in those reports (and they've been improved in 18f/analytics-reporter#164).
This looks like:
The labels aren't as clear and elegant as the rest, but I'm hoping this is fine for the interim.
I also went and added thresholds to the Windows and IE versions of the chart, since 18f/analytics-reporter#164 stopped doing bucketing into an `Other` …
=> Adds new browser/version combination data to data page

_includes/footer.html
Note: This depends on 18F/analytics-reporter#165 being merged and deployed to production.
This adjusts the link in the footer to point to the new location `sites.csv` will appear once auto-generated, and adjusts the link text to say "over 6,000 websites" instead of the current 4,000, which is in line with the current setting in https://github.com/18F/analytics-reporter/pull/165. 
If we make threshold changes in https://github.com/18F/analytics-reporter/pull/165 before merging, then the link text here will need a tweak again before merging.
Because I like including screenshots:
=> Updates link to point to auto-generated sites.csv

README.md, _includes/charts.html
It's a rough estimate, given how imperfect the data is, but given that a lot of people drastically overestimate how much traffic is from government networks, it seems worth adding a message.
Here's a screenshot:
This message will appear on agency-filtered pages too, but the message is explicit about "all agencies". Still, if there are agencies for which this is drastically different, we may want to consider some agency-specific messages.
=> Add note about traffic from government networks

_includes/footer.html
We're up to ~6,000 participating sites now (5,930-some at commit-time), so this updates the footer to say `6000` instead of `5000`.
=> Update number of participating sites

_includes/charts.html
The bulk CSV download link at the top of the Top 20 Domains over 30 Days tab was linking to just the top 20, instead of to all of them as intended.
=> Fix link to bulk download to all top domains

.travis.yml, _config.yml
This commit sets up continuous deploy with Travis. Whenever a changeset is merged into master, Travis will deploy the changes.
At this time, Travis deploys production and staging simultaneously. The deploy can be configured to have a branch that deploys production and a branch that deploys staging, but that seems like overkill for a static site. If it is a necessity though, I have the configuration on hand and can swap it in.
=> Setup continuous deploy

.codeclimate.yml, .eslintrc.yml, _config.yml
This commit adds configuration files for Code Climate and ESLint. These configs tell Code Climate to use the ESLint and CSSLint engines. Additionally, it tells Code Climate to ignore vendored JS and CSS.
The ESLint configs present in this commit simply tell ESLint to use the AirBnB config with no overrides.
=> Add codeclimate and ESList configs

js/index.js
Looks like this `console.log` was introduced in https://github.com/18F/analytics.usa.gov/commit/fda2c7ae2ce94a64de3ece67646940f26756a93f (https://github.com/18F/analytics.usa.gov/pull/404) by @rogeruiz. 
It seems unrelated to the code changes, and therefore likely committed by mistake. 
🚯
=> Remove what appears to be a debugging statement.

_includes/footer.html
After adjusting the threshold for the all-sites report to >9, the number moves back to around 4500 non staging, non-spurious sites.
=> Updating total number from all-sites report

_config.yml, _includes/charts.html, _includes/error.html, _layouts/default.html, css/public_analytics.scss
This commit adds a banner to the site which displays an error message when there are issues. The error is controlled using the `site_wide_error` property in the `_config.yml`. The property is an object with the following keys:
- `display`: Whether or not the banner should be displayed
- `title`: The title of the error message
- `body`: The body of the error message
Ref #452
=> Add site wide error banner

_config.yml
The hourly chart appears to be working again. This commit removes the error message broadcasting that it is broken.
=> Remove the error message about the hourly chart

_layouts/developer.html, developer.md
This commit adds a page at `/developer` which displays some documentation describing how to work with the analytics API. This commit also adds a layout for that page so it can be written in markdown instead of HTML.
Ref #455 
cc: @gbinal
=> Add a developer page to explain the API usage

css/public_analytics.scss
This PR uses CSS to change the devices breakdown (mobile, desktop, tablet) to title case — as the other breakdowns are. It’s been bothering me. 😅 
I took a look at changing this further upstream, but it seems that these are aggregated in a different place and that seemed like a Big Change for something that was a Small Bother — let me know if you’d rather I pursued that approach!
=> Capitalize the first letter of the devices list.

.travis.yml
Docker Compose mounts the site when working with it it. This leads to errors with syscalls when CI tries to build the site without Docker Compose. This commit resolves those issues by stopping Docker Compose before building the site, and then removing the files it has created.
=> Stop docker-compose before building site

developer.md
Adds a temporary alert well to the API developer docs page.
=> Add alpha alert to developer docs

README.md
Since we have Dockerized the repo, we need a way to version analytics.usa.gov so we can tag the Docker images. This commit adds some documentation to the repo to provide guidance to people building the Docker images about how to build, tag, and push them.
cc: @paolomainardi
=> Add instructions for building Docker images

developer.md
Following [these directions ](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#embedding-the-api-key-signup-form-on-your-own-documentation-site)- this should be good to go.
=> embedding the api signup form

_includes/charts.html
Addresses https://github.com/18F/analytics.usa.gov/issues/446.  
@jmhooper - just to confirm, does this look okay to you and does it make sense given what we return for the agency pages?  
If so, game to review and merge?
=> removing if=government filter for extra blub

.dockerignore, .travis.yml, Dockerfile.production, Makefile, README.md, nginx.conf
This commit updates the Dockerfile for the production Docker image so that is uses the nginx config in the repo.
The nginx config had to be modified a bit to make this possible. Specifically, an environment variable named `S3_BUCKET_URL`. This is the url for the data in the S3 bucket. This is done so the Docker image can handle this proxying action itself, instead of needing an nginx or apache config outside the container to handle this.
Since the nginx conf depends on the environment, it needs to be built at runtime with erb meaning ruby needed to be added to the container. Since ruby was added to the container, I went ahead and moved the site build into the container as well.
=> Update production Docker image to use custom nginx config

developer.md
Changes the API base url from `api.gsa.gov/systems/dap` to `api.gsa.gov/analytics/dap` to better fit the GSA API standards.
=> updating API URLs

nginx.conf
This commit modifies the NGINX configuration so that request to `/developers` redirect to `/developer`.
Closes #456
=> Redirect /developers to /developer

docs/maintenance.md
This commit adds documentation that describes the process for rotating cloud.gov credentials when needed.
=> Add documentation on rotating credentials

js/index.js
PR #505 changed the name of the heading when it loaded, but the new heading was being overwritten by JS. This commit updates the JS to use the new heading.
=> Add "& territories" to the international heading in JS

_includes/footer.html
This updates this part of the footer, which currently says it tracks 4,500 websites:
As of right now, it's 5,781 websites that appear in https://analytics.usa.gov/data/live/sites.csv (which is filtered to a certain threshold of visits). Without the threshold, there's 7,217 unique hostnames with at least 1 visit in the last 14 days, but I assume we're describing the count with the threshold.
=> Updating count of tracked websites from 4,500 to 5,700

js/index.js
This shows a few more Windows versions that are now below 1%, but still relevant to the thinking of site owners and users:
The additional rows extend that column, without lengthening the overall section (the Browsers column is still longer).
This is what it shows now on analytics.usa.gov, which leaves out Windows 8, XP, and Vista:
=> Lower display threshold for Windows versions from 1% to 0.1%

manifest.yml
Bret sent me a form email that cloud.gov was going to stop supporting cflinuxfs2 in late May and that we should upgrade. This commit does that upgrade.
=> Upgrade to clinuxfs3

README.md
I noticed that some of the links to sites which have reused this code base were either duplicates or non-functional. (And in the case of New Orleans, both.)
There's also an argument to remove two sites which are still up but appear unmaintained and non-functional at an app level:
* http://opendocs.cookcountyil.gov/analytics/
* https://datajerseycitynj.seamlessreports.com/
I recommend removing those as well, since it could backfire on the project to have folks check out non-functional sites, but since it might be a bug rather than the site being abandoned, I figured I'd just point them out first.
=> Remove duplicate websites and sites which have become non-functional

_config.yml
The massive amount of traffic to IRS today seems to have broken the GA realtime reports. Adding the banner to alert visitors.
=> Adding the sitewide error banner

manifest.yml
Adding a second instance as a production best practice. This should prevent downtime during deploy.
This might have already been applied via `cf scale` or within the cloud.gov dashboard, but this will make it explicit.
=> Add second instance

_config.yml
Realtime data in the Z3 View of the DAP GA account that powers the data on the analytics.usa.gov homepage is currently incorrect. This banner will alert users.
=> Activating sitewide banner

_config.yml
Updates copy for global warning message.
=> Copy change for warning banner

_config.yml
**Fake data is available for local development.** Restores fake data for local development. 
All environments. Unblocks local development, but impacts non-dev environments because these files are included.
Need to create a follow-up issue for excluding fake data on production.
**Before** - Excluding fake data
Uncomment line 4 in `_development.yml` and run `make dev`. Fake data doesn't load and a lot of `404` messages appear in console.
**After**
After removing `fake-data` for exclusion we can see 404's are gone and site loads properly.
1. Checkout this feature branch `jm-restore-local-data`.
2. Uncomment line 4 in `_development.yml`.
3. In terminal run `make dev` to run local environment.
4. Visit `localhost:4000`.
5. Site should load as expected with fake data.
=> Restore local data

.github/workflows/log_check_reminder.yml
This PR is the first to implement an automated scheduled reminder issue to open every Wednesday night at midnight to check the logs for security issues and other errors. This is a POAM.
None except for github actions
- Adds a GitHub action which must be in develop before we can test.
=> Add GitHub Action to open reminder issue for log checks

_includes/charts/sessions-today.html
This updates the data source for the today sessions to use an order array of values from `last-48-hours.json` report rather than `today.json`
Sampling level is automatic | today, top-pages-7-days | We can’t adjust precision in sampling, but we still get a metadata response when sampling has been performed.In some cases sampling is done while processing is still in progress, so !Golden.  When this occurs GA4 buckets values into the “(other)” key.  For reports like today, with date rage “today” -> “today” this makes a significant impact.  By updating the report date range to start from “yesterday”, we get a much more accurate SUM value, but need to handle some data clean-up on FE rendering.
-- | -- | --
=> update sessions today data source

_includes/charts/locations.html, _includes/charts/sessions-90-days.html, _includes/charts/sessions-today.html, _includes/data_download.html
Update copy to read 90 days for reporting where applicable.
**data downloads**
**sessions**
**top pages**
@smarina04 Still keep this at 30 days?
**current visitors and past 30 days for sessions**
****
=> Update chart copy

_includes/charts/top-pages.html, _includes/footer.html
- Fix small grammar issue in the footer.
- Remove the link to download the all-pages-realtime report from the top-pages 30 minutes tab
=> Adjust text/links for a hotfix

_includes/data_download.html
Resolves ticket: https://github.com/18F/analytics.usa.gov/issues/1199
=> Hotfix to remove total people online report from data page

nginx.conf.src
- Move DAP domains and touchpoints from default-src to script-src and img-src.
- Add connect-src to allow connection to Google Analytics and Touchpoints
=> [Tech Debt] Update CSP to be more restrictive

.github/workflows/log_check_reminder.yml
It's nice to use but it doesn't allow creating an issue that has the same title or description as an existing issue.
=> Stop using GuillaumeFalourd/open-issue-action to generate audit log review issues.

.github/workflows/ci.yml, .github/workflows/deploy.yml, apt.yml, buildpack.yml, manifest.yml, nginx.conf
- Set network policy in deploy job to allow traffic to the API interal route
- Use NGINX buildpack properly to allow interpolation and DNS server population
- Convert api key to api data gov secret
=> [Feature] Use internal route for API

js/components/data_downloads/DataDownloads.js, js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap
- These links point to top downloads reports instead of video plays.  Fix the links
=> [BugFix] Video play CSV download links

.github/workflows/log_check_reminder.yml
Removing Github from the list of systems that must be checked manually in the audit log review. @JJediny told me that audit logs for all GitHub orgs have recently started to be streamed to the GSA SoC, which is convenient, because Github audit logs have been hard to access (only organizational owners may view audit logs). Now the SoC can be responsible for monitoring Github audit logs.
=> Update the audit log review reminder Github action

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/manual_deploy_to_dev.yml, ga4-data/live/top-downloads-30-days.json, ga4-data/live/top-downloads-7-days.json, ga4-data/live/top-downloads-yesterday.json, js/components/dashboard_content/TopDownloads.js, js/components/dashboard_content/__tests__/TopDownloads.spec.js, js/components/dashboard_content/__tests__/__snapshots__/TopDownloads.spec.js.snap, js/components/dashboard_content/__tests__/__snapshots__/TopDownloadsAndVideoPlays.spec.js.snap, js/lib/chart_helpers/__tests__/formatters.spec.js, sass/pages/root/_secondary-data.scss, spec/factories/reports/download.js
The site has a bug when files which appear in the Top Downloads section have spaces in the filenames.  The HREF for the link to the file will be incorrect.
This PR ensures that the HREF goes to the correct URL with spaces encoded.
=> [Bugfix] Handle spaces in download filenames and handle file locations with different domains from the event page

_data/agencies.json
=> [Feature] Record page helpful free text feedback in GA -- Staging

.github/workflows/ci.yml, .github/workflows/deploy.yml
This PR is related to the Trello card [Implement subresource integrity for all analytics.usa.gov application components](https://trello.com/c/jQA2F0JX). npm audit signatures "verifies the registry signatures of downloaded packages" that "you download from the public npm registry, or any registry that supports signatures". It also verifies the ["provenance attestations"](https://slsa.dev/spec/v1.0/provenance) of any packages that provide them.
=> Add 'npm audit signatures' to CI workflow.
