js/index.js

Format top site visit counts with commas

---

index.html

`dap.18f.us` -> `analytics.usa.gov`

Switching URLs to real domain data source

---

css/public_analytics.css

going from `#aaa` to `#E4E4E4`

lightening up the grey borders

---

demo/index.html

index to include .csv of DAP domains

---

js/index.js

Good times. Looking forward to DAP changes that put some of these behind us.
We're still planning on doing a generalized exception function for petitions.whitehouse.gov, there's just nothing trending at the moment for me to test on. However, even that will be an interim for when DAP stops lowercasing URIs.

Various hardcoded URL and title exceptions

---

index.html

include all sites .csv

---

sass/public_analytics.css.scss

removing blue border on bar focus

update sass with change in pr #193

---

index.html

As per DAP [Implementation Guide](https://www.digitalgov.gov/files/2015/02/GSA-DAP-UA-Code-Quick-Guide-15-01-30-v1-02_mvf.pdf), this should allow for recording of the json downloads.

Add exts into DAP script to capture json downloads

---

index.html

with UA code provided by Gray.

added GA snippet

---

Gemfile.lock
index.html

Added a link to jquery, some new class names and some code reporting the events.

added tracking for specific events

---

index.html
js/index.js

This takes the work in https://github.com/18F/analytics.usa.gov/commit/d2d9a9072d0bc4c2b9203a6d430b400d09f10144 in #225 and applies it to fix the tabs. #225 had other commits from #221 that weren't ready for merging yet.
Since this is a commit taken directly from #225 which I've already reviewed, minus some `console.log` statements, I'm going to consider it reviewed and self-merge.

Fix tabs (standalone)

---

index.html

-people on each site in realtime
-people on each site over 30 days
-visits by city over 90 days
-visits by country over 90 days
-top 100 downloads in realtime
-top 100 downloads over 30 days

added 6 new links to download data

---

index.html
js/index.js

Includes:
-minor copy changes
-2 new GA events for when people click on the top downloads links
-attempted bug fix for the '2 others' bug

attempted bug fix for 'other' bug, new GA events and copy changes

---

js/index.js

This removes some unnecessary URL rewriting we were doing, and updates IRS links to go their canonical protocol.

Cleanup some hardcoded URL exceptions

---

_agencies/93sx-sba.html
_agencies/f9sl-commerce.html
_agencies/fi23d-nara.html
_agencies/msi9-energy.html
_agencies/mzomd-doi.html
_agencies/x03sk-epa.html

Creating pages for SBA, Commerce, NARA, Energy, DOI, and EPA

Adding SBA, Commerce, NARA, Energy, DOI, and EPA

---

_layouts/default.html

This is a test of DAP v3.0 in GTM

Swap DAP script for GTM container

---

_layouts/default.html

Resolves https://github.com/18F/analytics.usa.gov/issues/256.

Add notes on threshold on data downloads

---

_layouts/agencies.html
_layouts/default.html

`anatlyics.usa.gov` link should now go to the root page. 
[Resolves #294]

Upper left link now goes to home page

---

_layouts/agencies.html
_layouts/default.html
fake-data/top-downloads-yesterday.json

Changing top downloads last week to top downloads yesterday
Do not merge until data feed is active.

Top downloads yesterday

---

_layouts/agencies.html
_layouts/default.html
css/public_analytics.scss
js/index.js

Tried to make the select box large enough to accomodate all screen sizes. I also Added another select box that hides on large screens and shows on small screens, and floats underneath the Page header at lower resolution.(the other select box conversely shows at large screen sizes, and hides at small).

Agency nav style

---

_layouts/default.html

GTM test completed. Moving back to dap.digitalgov.gov

Switch back to normal DAP script

---

_config.yml

Rename "All Agencies" to "All Participating Websites"

---

css/public_analytics.scss

Degrades the font-size of the select agency navigation for lower res mobile. resolve #311

Adjusted font size of navigation for mobile screen

---

_layouts/agencies.html
_layouts/default.html
css/public_analytics.scss

Addresses #319 
Pretty simple a background color change of some buttons to a slightly darker blue, and some extra div attributes.

508 compliance fixes

---

_layouts/agencies.html
_layouts/default.html
css/public_analytics.scss

Added a Technical difficulty banner (temporary).

Technical difficulties

---

_layouts/agencies.html
_layouts/default.html

Removed technical difficulties banner.

Removed tech. diff

---

README.md

Instructions for adding new agencies. [Resolves  #342]

Adding instructions for adding new agencies to README.md

---

css/public_analytics.scss

Fixes the issue with the dropdown arrow not appearing by placing the SVG's URI directly in the CSS.

specify SVG data uri for dropdown

---

_includes/header.html

Added a default sort to the Navigation dropdown.
Addresses #366

Added sorting by name for Navigation dropdown

---

_agencies/agency-international-development.html
_agencies/agriculture.hmtl
_agencies/defense.html
_agencies/general-services-administration.html
_agencies/health-human-services.html
_agencies/homeland-security.html
_agencies/housing-urban-development.html
_agencies/labor.html
_agencies/national-science-foundation.html
_agencies/nuclear-regulatory-commission.html
_agencies/office-personnel-management
_agencies/postal-service.html
_agencies/social-security-administration.html
_agencies/state.html
_agencies/transportation.html
_agencies/treasury.html

This PR should create the agency pages for #365.  We shouldn't merge until the underlying data points are created.

[HOLD] Adding agencies

---

css/public_analytics.scss

Header dropdown should be full-width on small screens

---

README.md

http://analytics.douglascounty-ne.gov/

Adding new dashboard

---

README.md

instead of url, linking to more descriptive text

describing adopters

---

404.html
css/public_analytics.scss

A possible solution to the 404 page styling issues.
Fixes #388

Fix the 404 page

---

_includes/footer_scripts.html

as part of recently released v3.1 options

Adding async

---

.about.yml

edited to account for the dashboard including some non ".gov" domains.

minor .gov domain change

---

_agencies/executive-office-president.html
_agencies/health-human-services.html
_data_pages/executive-office-president.html
_data_pages/health-human-services.html

Adding agencies

---

_includes/footer_scripts.html
_includes/gtm_iframe.html
_includes/head.html
_layouts/default.html

Swapping DAP `<script>` in HTML for GTM container with DAP tag.

Adding in GTM container for DAP code

---

developer.md

We changed up the available reports in https://github.com/18F/analytics-reporter/pull/221. This commit updates the developer page to reflect the available reports.

Update developer page with new reports.

---

developer.md

This commit adds the version numbers to the example API request URLs

Add version numbers to API paths

---

developer.md

two more small semantic changes

---

developer.md

@jmhooper or @tdlowden - game to check and merge?

fixing endpoint url

---

docs/procedures.md

This is my recommended enhancement to the weekly security check process. Having a clear set of steps for the person doing the monitoring to follow is preferred so that the right things are checked for.

Recommended enhancement of weekly security check

---

docs/procedures.md

Added step by step instructions per guidance

step by step instructions for accounts

---

Gemfile
Gemfile.lock

This commit adds version specifications to the gems in the Gemfile. This
was motivated by checking Gemnasium for out of date gems.

Add versions to gems in Gemfile

---

docs/procedures.md

For SSP & addressing POA&M purposes

Swapping Tim for Gray as System Owner

---

.circleci/config.yml
circle.yml

Circle is sunsetting the old V1 config this summer. This commit moves us
over to v2.

Update to CircleCI v2

---

_includes/head.html

Shorten text and update the link to the repo, in the HTML comments.

Update text and link to repo

---

developer.md

update developer docs for future filters

---

_config.yml

HOLD FOR SHUTDOWN Add shutdown banner

---

_config.yml

Removing shutdown banner

---

_includes/footer.html

Resolves Issue #558
footer.html

Swap link to API docs

---

nginx.conf

updating api doc redirects

---

.circleci/config.yml
bin/deploy-ci.sh

This PR wires up CI such that deploying the app in CI should not cause downtime

Use ZDT push in CI

---

_includes/footer.html

Adding in some info that sampling can occur. Open to suggestions on language edits.

Add a note on sampling

---

_includes/footer.html
_layouts/default.html
js/lib/blocks.js

Resolves Issue #736 
Adding rel="noopener" to target=_blank links

Tdlowden patch 8

---

js/lib/blocks.js

remaining rel="noopener" fixes

.attr('rel', 'noopener')

---

_includes/footer.html

Making data plural, as is proper

---

README.md

addresses the issue @anselmbradford identified here: https://github.com/18F/analytics.usa.gov/pull/507

improve ul numbering and whitespace

---

README.md

Resolves Issue #890 
Added link to State of Delaware analytics site.
README.md

Added State of Delaware

---

nginx.conf

Testing Syntax Fixes for nginx.conf 3

---

nginx.conf

Testing Syntax Fixes for nginx.conf 4

---

nginx.conf

Testing Syntax Fixes for nginx.conf 5

---

manifest.yml
new_boot.sh
nginx.conf
nginx_snips/if_S3_BUCKET_URL.txt
nginx_snips/if_edi.txt
nginx_snips/if_force_https.txt
nginx_snips/if_htpasswd.txt

Different method, make new bootstrap script, do "if" checks there, edit nginx.conf accordingly.

---

manifest.yml

Try without start command

---

manifest.yml

Moving to nginx buildpack 4

---

manifest.yml

Moving to nginx buildpack 5

---

manifest.yml

Moving to nginx buildpack 6

---

manifest.yml
new_boot.sh
nginx.conf
nginx_new.conf

Moving to nginx buildpack 9

---

manifest.yml

Moving to nginx buildpack 10

---

manifest.yml

Moving to nginx buildpack 11

---

manifest.yml

Moving to nginx buildpack 12

---

nginx.conf

Moving to nginx buildpack 13

---

nginx.conf

Moving to nginx buildpack 15

---

manifest.yml
nginx.conf

Restore Nginx file

---

nginx.conf

Moving to nginx buildpack 18

---

nginx.conf

Moving to nginx buildpack 20

---

nginx.conf

Moving to nginx buildpack 21

---

nginx.conf

Moving to nginx buildpack 22

---

nginx.conf

Moving to nginx buildpack 23

---

nginx.conf

Moving to nginx buildpack 24

---

nginx.conf

Moving to nginx buildpack 25

---

nginx.conf

Moving to nginx buildpack 28

---

nginx.conf

Moving to nginx buildpack 29

---

nginx.conf

Moving to nginx buildpack 30

---

manifest.yml
nginx.conf
nginx/conf/nginx.conf

Try with different nginx folder structure.

---

Staticfile
nginx/conf/includes/events.conf
nginx/conf/includes/http.conf

Try via include files

---

nginx/conf/includes/events.conf
nginx/conf/includes/http.conf

Adjust conf files for nginx

---

nginx/conf/includes/events.conf
nginx/conf/includes/http.conf

Add brackets back

---

nginx/conf/includes/events.conf
nginx/conf/includes/http.conf

Remove events file

---

nginx/conf/includes/http.conf

Reformat http

---

nginx/nginx.conf

Reset nginx.config

---

manifest.yml

Reset nginx.config 2

---

nginx/nginx.yml

Try replacing nginx/conf.d/default.conf 4

---

nginx/nginx.yml

Try replacing nginx/conf.d/default.conf 5

---

Staticfile
nginx.conf
nginx/conf/includes/locations.conf

Split out locations

---

Staticfile
nginx.conf

Split out locations 2

---

Staticfile

Split out locations 3

---

Staticfile

Split out locations 4

---

Staticfile
nginx/conf/includes/locations.conf

Split out locations 5

---

Staticfile

Split out locations 6

---

nginx.conf

Change back to nginx buildpack 2

---

nginx.conf
orig.conf

Change back to nginx buildpack 3

---

entrypoint.sh
manifest.yml

Change back to nginx buildpack 4

---

apt.yml
manifest.yml

Change back to nginx buildpack 5

---

.cfignore

.cfignore file

---

nginx.conf

Use real nginx.conf from prod

---

nginx.conf

Add commentent out listen line

---

nginx.conf

Take out mime types

---

nginx.conf

comment out auth

---

nginx.conf

Change root path

---

entrypoint.sh
nginx.conf

S3 Bucket troubleshooting 1

---

nginx.conf

S3 Bucket troubleshooting 2

---

apt.yml
nginx.conf

S3 Bucket troubleshooting 3

---

apt.yml
entrypoint.sh

S3 Bucket troubleshooting 4

---

.circleci/config.yml
entrypoint.sh
nginx.conf

S3 Bucket troubleshooting 5

---

.circleci/config.yml

S3 Bucket troubleshooting 6

---

.circleci/config.yml

S3 Bucket troubleshooting 7

---

.circleci/config.yml

S3 Bucket troubleshooting 8

---

.circleci/config.yml

S3 Bucket troubleshooting 9

---

.circleci/config.yml

Try envsubst without flags and single quotes around env var

---

.circleci/config.yml

Try envsubst without flags and single quotes around env var 3

---

nginx.conf.src

Mess with CORS

---

nginx.conf.src

Mess with CORS 2

---

nginx.conf.src

Mess with CORS 3

---

nginx.conf.src

Mess with CORS 5

---

nginx.conf.src

Mess with CORS 6

---

nginx.conf.src

Mess with CORS 7

---

nginx.conf.src

Mess with CORS 8

---

_config.yml

Change Data URL

---

.circleci/config.yml
_config.yml

Make _config.yml dynamic

---

.circleci/config.yml

Make _config.yml dynamic 2

---

.circleci/config.yml

Make _config.yml dynamic 3

---

.circleci/config.yml

Make _config.yml dynamic 4

---

.circleci/config.yml

Make _config.yml dynamic 5

---

.circleci/config.yml
README.md
nginx.conf.src

HOTFIX Resolves S3 bucket EVN Issue.

Hotfix for S3 Bucket

---

.circleci/config.yml

Some staging typos

---

_config.yml

Update message due to Marina's comments 3

---

_includes/footer_scripts.html

Added DAP script to footer

---

.circleci/config.yml

Change CF creds per env

---

.circleci/config.yml

Change sed for stage deploy for S3

---

_data/agencies.json
_includes/head.html

Removes stylesheet and fixes OPM dropdown selection.

Removed stylesheet and fixed OPM drop down

---

.circleci/config.yml
_data/agencies.json

Added `npm run copy-assets` to `.circleci/config.yml` for copying `uswds 3` assets for building.

Added copyAssets to circleci pipeline, updated agencies for `develop`

---

.circleci/config.yml

Adds `develop_deploy` job to run on `develop` branch for **circleci**

Added develop_deploy for develop branch

---

_includes/charts/sessions-90-days.html

Removed language about data for sessions block

---

js/lib/blocks.js

Fixed eslint error

---

ga4-data/live/top-downloads-yesterday.json
spec/formatters.spec.js

Fix tests for `formatFile` function.

Fix test for formatFile

---

package.json

This PR adds the newrelic apm agent as a package inside of package.json
None
None
- Adds NewRelic APM agent.

Add newrelic apm agent to package.json

---

Gemfile
Gemfile.lock
newrelic.yml

New Relic setup for analytics.usa.gov

---

_includes/charts/top-pages.html

See https://github.com/18F/analytics.usa.gov/issues/1144 for details

Disabled now button and data

---

_includes/charts.html
css/public_analytics.scss

See details for changes https://github.com/18F/analytics.usa.gov/issues/1144

Removed now button and set 7 days

---

.circleci/config.yml

Remove Legacy Production Steps
Resolves Issue where deployment pipeline was unsuccessful.  This has already been applied to the master branch, so this PR makes staging and master branches consistent.

Hotfix to allow prod deploy

---

_includes/charts.html
css/public_analytics.scss

Redo merge for https://github.com/18F/analytics.usa.gov/issues/1144

Re-merge staging to production with config hotfix

---

.circleci/config.yml

Remove duplication in CI and fix deployment

---

_includes/charts.html

Solve staging conflicts

---

spec/formatters.spec.js
spec/transformers.spec.js

Fix js specs that were marked pending

---

_includes/data_download.html

Frequency was every 5 minutes for UA, GA4 only updates every 30 mins

Update frequency label on realtime report data

---

_includes/footer.html

Disable footer link to second-level-domains temporarily

---

_includes/charts/top-pages.html
_includes/footer.html

Staging deploy to fix download link for top-10000-domains-30 days report and disable sites report link in footer

---

_includes/charts/demographics-30-days.html

Add section headline and horizontal rule above device charts

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
package-lock.json
package.json

- Add timing flag for npm install
- Add workaround for slowness due to pa11y dependency puppeteer
- Add note to remove once GitHub issue is addressed

Address CI slowness on npm install

---

_includes/charts/realtime-visitors.html

Resolves ticket: https://github.com/18F/analytics.usa.gov/issues/1215

Hotfix: Update wording on realtime visitor description to include 'federal' - Staging Deployment

---

_includes/charts/realtime-visitors.html

Resolves ticket: https://github.com/18F/analytics.usa.gov/issues/1208

Make realtime visitor description dynamic

---

.github/workflows/log_check_reminder.yml

Update the body of the audit log review issue

Update the body of the audit log review issue

---

.github/workflows/log_check_reminder.yml

Use the correct Ubuntu date command.

Fix date in title of audit log review issue.

---

manifest.yml

[Tech Debt] Move route creation to manifest -- Staging

---

manifest.yml

[Tech Debt] Move route creation to manifest -- Production

---

_data/agencies.json
eslint.config.js
js/components/agency_select/AgencySelect.js

[Feature] Support subagencies and add NPS/FBI

---

_data/agencies.json
_includes/header.html
eslint.config.js
js/components/agency_select/AgencySelect.js
js/components/agency_select/__tests__/AgencySelect.spec.js
js/components/agency_select/__tests__/__snapshots__/AgencySelect.spec.js.snap
sass/components/_agency-select.scss
sass/layout/_header.scss

[Feature] Refactor header element positioning -- Staging

---

sass/components/_agency-select.scss

[Bugfix] Revert width changes to agency select on data pages -- Staging

---

js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap

[Feature] Update screen size report to screen resolution -- Staging

---

js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap
sass/components/_agency-select.scss

[Feature] Update screen size report to screen resolution -- Production

---

js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap

[Bugfix] Correct device model report name -- Staging

---

js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap

[Bugfix] Correct device model report name -- Production

---

_data/agencies.json

[Feature] Add US Courts agency -- Staging

---

_data/agencies.json
js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap

[BugFix] Video play CSV download links -- Production

---

_includes/analytics_definitions.html

Addresses ticket: https://trello.com/c/mTDGkTD5

[Feature] Add screen resolution dimension to demographics report definition

---

js/components/data_downloads/DataDownloads.js
js/components/data_downloads/__tests__/__snapshots__/DataDownloads.spec.js.snap

Addresses ticket: https://trello.com/c/BKr7qVdR

[Feature] Increase limit on page level reports from 10k to 100k

---

nginx.conf

[Tech Debt] Log NGINX errors to stderr

---

_data/agencies.json

[Feature] Update CNCS display name to AmeriCorps -- Staging

---

_data/agencies.json
nginx.conf

[Feature] Update CNCS display name to AmeriCorps -- Production

---

js/components/touchpoints_page_helpful_survey/TouchpointsPageHelpfulSurvey.js

[Feature] Record page helpful free text feedback in GA

---

js/components/touchpoints_page_helpful_survey/TouchpointsPageHelpfulSurvey.js
js/components/touchpoints_page_helpful_survey/__tests__/TouchpointsPageHelpfulSurvey.spec.js
js/components/touchpoints_page_helpful_survey/__tests__/__snapshots__/TouchpointsPageHelpfulSurvey.spec.js.snap
package.json

[BugFix] Update touchpoints header selector -- Staging

---

.github/workflows/ci.yml
js/components/dashboard_content/DashboardContent.js

[Feature] Total users card populated by session_start event count

---

.github/workflows/ci.yml

[Tech Debt] Fix bug in deploy 'if' expression -- Staging

---

js/components/dashboard_content/SidebarContent.js
js/components/dashboard_content/__tests__/__snapshots__/SidebarContent.spec.js.snap

[BugFix] Update broken link to 10k domain report -- Staging

---

.github/workflows/ci.yml
js/components/dashboard_content/SidebarContent.js
js/components/dashboard_content/__tests__/__snapshots__/SidebarContent.spec.js.snap

[BugFix] Update broken link to 10k domain report -- Production

---

js/components/accordion/Accordion.js
js/components/accordion/AccordionContent.js
js/components/accordion/AccordionHeader.js
js/components/dashboard_content/DashboardContent.js
js/components/dashboard_content/DeviceDemographics.js
js/components/dashboard_content/TrafficSources.js
js/components/dashboard_content/__tests__/__snapshots__/DeviceDemographics.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TrafficSources.spec.js.snap
sass/_uswds-overrides.scss

[Feature] Add accordions to dashboard

---

_data/agencies.json

Add USPTO, Forest Service, OSHRC, Food and Nutrition Service, and NIST

[Feature] Add new agencies

---

_includes/dashboard_content.html
_includes/header.html
js/components/agency_select/AgencySelect.js
js/components/agency_select/__tests__/__snapshots__/AgencySelect.spec.js.snap
nginx.conf
sass/components/_agency-select.scss
sass/layout/_header.scss

[Feature] Add search functionality

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

[Tech Debt] Update setup-ruby action to v1

---

_data/agencies.json

[Feature] Add air force, army, navy subagencies

---

_data/agencies.json

[Feature] Add NLM subagency

---

_data/agencies.json

[Feature] Add Forest Service

---

_includes/head.html
_includes/header.html

[Feature] Update site verification tag -- Staging

---

_data/agencies.json

[Feature] Add DHA, Marines, Space Force

---

_includes/head.html
_includes/header.html

[Feature] Add DHA, Marines, Space Force -- Staging

---

package-lock.json

[Security] npm audit fix undici -- Staging

---

_data/agencies.json
package-lock.json

[Security] npm audit fix undici -- Production

---

_includes/analytics_definitions.html
js/components/dashboard_content/DashboardContent.js
js/components/dashboard_content/TopDownloads.js
js/components/dashboard_content/__tests__/__snapshots__/TopDownloads.spec.js.snap

[Feature] Remove time periods from tooltips/definitions -- Staging

---

_includes/dashboard_content.html
_includes/touchpoints_page_helpful_survey.html
_layouts/default.html
ga4-data/analytics.usa.gov/was-this-page-helpful-30-days.json
js/components/dashboard_content/SidebarContent.js
js/components/page_helpful_survey_score/PageHelpfulSurveyScore.js
js/components/page_helpful_survey_score/index.js
js/lib/react_setup.js
package-lock.json
package.json
sass/components/_index.scss
sass/components/_page_helpful_survey_score.scss
sass/components/_touchpoints_page_helpful_survey.scss

[Feature] Add page helpful score for the site

---

_data/agencies.json

add cdc.json

---

README.md
_data/agencies.json
_includes/analytics_definitions.html

add cdc subagency

---

_data/agencies.json

Update alphabetical order for CDC.json

---

.github/workflows/log_check_reminder.yml
_data/agencies.json

update alphabetical order

---

_data/agencies.json

[Tech Debt] Fix typo

---

_data/agencies.json

adding osc agency to staging

---

_includes/header.html
_includes/visualizations.html
images/dap-watermark.svg
js/components/dashboard_content/BrowsersChart.js
js/components/dashboard_content/DevicesChart.js
js/components/dashboard_content/OperatingSystemsChart.js
js/components/dashboard_content/ScreenResolutionsChart.js
js/components/dashboard_content/TopCities.js
js/components/dashboard_content/TopCountries.js
js/components/dashboard_content/TopDownloads.js
js/components/dashboard_content/TopLanguages.js
js/components/dashboard_content/TopPages.js
js/components/dashboard_content/TopSessionChannelGroupChart.js
js/components/dashboard_content/TopSessionSourceMediumChart.js
js/components/dashboard_content/TopVideoPlays.js
js/components/dashboard_content/__tests__/__snapshots__/BrowsersChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/DeviceDemographics.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/DevicesChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/OperatingSystemsChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopCities.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopCountries.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopDownloads.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopLanguages.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopVideoPlays.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TrafficSources.spec.js.snap
js/components/visualizations/TopPagesCircleGraph.js
sass/layout/_header.scss

[Feature] Add visualization links to header

---

js/components/dashboard_content/BrowsersChart.js
js/components/dashboard_content/DevicesChart.js
js/components/dashboard_content/OperatingSystemsChart.js
js/components/dashboard_content/ScreenResolutionsChart.js
js/components/dashboard_content/TopCities.js
js/components/dashboard_content/TopCountries.js
js/components/dashboard_content/TopDownloads.js
js/components/dashboard_content/TopLanguages.js
js/components/dashboard_content/TopPages.js
js/components/dashboard_content/TopSessionChannelGroupChart.js
js/components/dashboard_content/TopSessionSourceMediumChart.js
js/components/dashboard_content/TopVideoPlays.js
js/components/dashboard_content/__tests__/OperatingSystemsChart.spec.js
js/components/dashboard_content/__tests__/TopDownloads.spec.js
js/components/dashboard_content/__tests__/__snapshots__/BrowsersChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/DeviceDemographics.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/DevicesChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/OperatingSystemsChart.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopCities.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopCountries.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopDownloads.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopLanguages.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TopVideoPlays.spec.js.snap
js/components/dashboard_content/__tests__/__snapshots__/TrafficSources.spec.js.snap
js/components/visualizations/TopPagesCircleGraph.js

[Feature] Remove yesterday time period from all charts

---

_data/agencies.json

Adds ACF subagency under HSS

---

_data/agencies.json

Dev-->Staging Adds ACF subagency

---

_data/agencies.json

Add DLA under DOD
